version: "3.9"
    
services:
  db:
    image: mariadb:10.3.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: libki
      MYSQL_USER: libki
      MYSQL_PASSWORD: libki
    
  libki:
    depends_on:
      - db
    image: libki/libki-server:latest
    ports:
      - "3000:3000"
    restart: always
    environment:
      LIBKI_DB_DSN=dbi:mysql:libki;host=db;port=3306
      LIBKI_DB_USER=root
      LIBKI_DB_PASSWORD=password
      LIBKI_DB_HOST=db
      LIBKI_DB_PORT=3306
      LIBKI_DB_DATABASE=libki
      TZ=America/New_York

volumes:
  db_data: {}
